### PR TITLE
Pickpocket fix

### LINKED ISSUE #52: [Crash] Pickpocketing crashes the client if the NPC changes the inventory content
With two players connected to a server A and B.
1) A starts pick pocketing player B
2) Player B modifies their inventory 
3) A crashes

Potential fix : Cache inventory changes received while in menus and apply them when possible.

### PR DESCRIPTION
**Pull request by Dejauxvue**
should fix crashes when a player acceses inventory while being pickpocketet by another player
invenotry changes are cached until player leaves inventory

fixes #52

### CODE REVIEW

**Comment by zxyxz** [comment]
great !

**Comment by schme16** [comment]
Nice work @Dejauxvue! Hopefully it gets merged soon!

**Comment by Dejauxvue** [comment]
Tested it with skyrim in a virtualbox, could reproduce the bug on master an it doesn't occur in this version

**Comment by LordKanelsnegle** [comment]
Tested this with @Dejauxvue for half an hour or so under a variety of conditions and it seems the latest build does in fact fix this problem. Nice work ^-^

**Comment by Dejauxvue** [comment]
thanks!
We tested dropping and picking upd and (un)equipping items by player A while player B inspects A's inventory.
No crashes.
After synchronizing via (un)equip the inventories were consistent for player A and player B

We had some weird effects that I think are attributed to the fact that inventories are only synchronized on (un)equip
So, I think this is another issue

**Comment by Dejauxvue** [comment]
> 
> 
> should fix crashes when a player acceses inventory while being pickpocketet by another player
> invenotry changes are cached until player leaves inventory

My initial understanding of the problem was a bit off. This pull request should fix Issue 52

**Pull request merged**
