### PR TITLE
Change suggested version of visual studio to 16.8

### PR DESCRIPTION
**Pull request by Etragas**
This PR is a follow up to #60 and is a fix for #61

I tried to use sol.hpp from the 3.2.1 release but encountered the same compilation issues. So I'm putting this pr back up.

I tried changing the window_build to use 16.8 since azure pipelines were previously crashing due to the same issue. But the vsBuild and msBuild tasks do not support this version.

### CODE REVIEW

**Comment by yamashi** [comment]
So the changes to windows-build.yml didn't help?

**Comment by Etragas** [comment]
Sadly no. I think the issue is that the vsVersion flag doesn't support that version.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops
image

I tried setting it anyway, but the builds still failed with the same errors. I was surprised the build didn't fail due to an unsupported flag.

It seems that under the hood vsVersion passes the flag to [msBuild](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops) which will ignore the flag and use latest if the flag is misconfigured e.g when it's 16.8 

I also did a git grep and found no examples where the vsVersion is set to 16.8 https://grep.app/search?q=vsVersion%3A%2016.

**Comment by Etragas** [comment]
I didn't try downgrading to previous versions for the pipeline (e.g 16.0, 15.0), but that might work.

**Review by yamashi — APPROVED** [review]

**Comment by Etragas** [comment]
@yamashi I can't merge this PR atm, probably because of the failing pipelines. And I don't think I can force a merge. So someone else will have to force merge.

**Pull request merged**
